-- +migrate Up
-- SQL in section 'Up' is executed when this migration is applied

-- MySQL Script generated by MySQL Workbench
-- Sat Jul  27 16:09:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SpinnrTechnology
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SpinnrTechnology
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SpinnrTechnology` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `SpinnrTechnology` ;


-- -----------------------------------------------------
-- Table `SpinnrTechnology`.`Level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpinnrTechnology`.`Level` (
    `ID` INT AUTO_INCREMENT PRIMARY KEY,
    `Name` VARCHAR(255) NOT NULL,
    `LV` INT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SpinnrTechnology`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpinnrTechnology`.`Player` (
    `ID` INT AUTO_INCREMENT PRIMARY KEY,
    `Name` VARCHAR(255) NOT NULL,
    `LevelID` INT NOT NULL,
    FOREIGN KEY (`LevelID`) REFERENCES `Level`(`ID`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SpinnrTechnology`.`PrizePool`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpinnrTechnology`.`Reservation` (
    `ID` INT AUTO_INCREMENT PRIMARY KEY,
    `RoomID` INT NOT NULL,
    `Date` DATETIME NOT NULL,
    FOREIGN KEY (`RoomID`) REFERENCES `Room`(`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SpinnrTechnology`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpinnrTechnology`.`Room` (
    `ID` INT AUTO_INCREMENT PRIMARY KEY,
    `Name` VARCHAR(255) NOT NULL,
    `Status` INT NOT NULL,
    `Description` TEXT NOT NULL,
    `PlayerIDs` TEXT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SpinnrTechnology`.`GameLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpinnrTechnology`.`GameLog` (
    `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `PlayerID` VARCHAR(255) NOT NULL,
    `Action` VARCHAR(255) NOT NULL,
    `Timestamp` DATETIME NOT NULL,
    `Details` TEXT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SpinnrTechnology`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpinnrTechnology`.`Payment` (
    `ID` INT AUTO_INCREMENT PRIMARY KEY,
    `Method` VARCHAR(255) NOT NULL,
    `Amount` FLOAT NOT NULL,
    `Describle` TEXT NOT NULL,
    `Timestamp` DATETIME NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SpinnrTechnology`.`Challenge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpinnrTechnology`.`Challenge` (
    `ID` INT AUTO_INCREMENT PRIMARY KEY,
    `PlayerID` VARCHAR(255) NOT NULL,
    `Amount` FLOAT NOT NULL,
    `Status` VARCHAR(50) NOT NULL,
    `Won` BOOLEAN NOT NULL,
    `CreatedAt` DATETIME NOT NULL,
    `Probability` FLOAT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `SpinnrTechnology`.`PrizePool`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpinnrTechnology`.`PrizePool` (
    `ID` INT AUTO_INCREMENT PRIMARY KEY,
    `Amount` FLOAT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Insert the single record into PrizePool
-- -----------------------------------------------------
INSERT INTO PrizePool (amount)
SELECT 0
WHERE NOT EXISTS (SELECT 1 FROM PrizePool);

-- -----------------------------------------------------
-- Create a trigger to prevent additional inserts
-- -----------------------------------------------------
DELIMITER //
CREATE TRIGGER prevent_prizepool_insert
BEFORE INSERT ON PrizePool
FOR EACH ROW
BEGIN
    DECLARE record_count INT;
    SELECT COUNT(*) INTO record_count FROM PrizePool;
    IF record_count > 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Only one record is allowed in the PrizePool table';
    END IF;
END;//
DELIMITER ;





SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- +migrate Down
-- SQL section 'Down' is executed when this migration is rolled back

-- -----------------------------------------------------
-- Table `SpinnrTechnology`.`Challenge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SpinnrTechnology`.`Challenge` ;
-- -----------------------------------------------------
-- Schema SpinnrTechnology
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SpinnrTechnology` ;