-- +migrate Up
-- SQL in section 'Up' is executed when this migration is applied

-- MySQL Script generated by MySQL Workbench
-- Sat Jul  27 16:09:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SpinnrTechnology
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SpinnrTechnology
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SpinnrTechnology` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `SpinnrTechnology` ;

-- -----------------------------------------------------
-- Table `SpinnrTechnology`.`Challenge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpinnrTechnology`.`Challenge` (
    `ID` INT AUTO_INCREMENT PRIMARY KEY,
    `PlayerID` VARCHAR(255) NOT NULL,
    `Amount` FLOAT NOT NULL,
    `Status` VARCHAR(50) NOT NULL,
    `Won` BOOLEAN NOT NULL,
    `CreatedAt` DATETIME NOT NULL,
    `Probability` FLOAT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- +migrate Down
-- SQL section 'Down' is executed when this migration is rolled back

-- -----------------------------------------------------
-- Table `SpinnrTechnology`.`Challenge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SpinnrTechnology`.`Challenge` ;
-- -----------------------------------------------------
-- Schema SpinnrTechnology
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SpinnrTechnology` ;